In [23]:
## Basic Operations with TF

#### The notebook explains how to implement basic operation for TF 

In [1]:
import tensorflow as tf

/home/clemente/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.12.0


In [3]:
#Let's assign a constant string to a variable
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
#Printing will not work
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
#Assigning the operation to a variable
operation_1 = hello+world

In [8]:
#We need to run a session and run the operation
with tf.Session() as sess:
    result = sess.run(operation_1)

In [9]:
#Then you can print the result
result

b'HelloWorld'

In [10]:
#Same goes for when assigning a constant
const_a = tf.constant(10)
const_b = tf.constant(20)
result = const_a+const_b

In [11]:
with tf.Session() as sess:
    result = sess.run(result)

In [12]:
result

30

In [13]:
#Same goes for when assigning a constant
const_a = tf.constant(10)
const_b = tf.constant(20)
result = const_a+const_b

In [14]:
#Or we can use the interactive session and then run any operation with eval()
sess = tf.InteractiveSession()

In [15]:
result.eval()

30

In [16]:
#Declaring a 4x4 matrix of 10
fill_mat = tf.fill((4,4),10)

In [17]:
#And priting it
fill_mat.eval()

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)

In [18]:
#More printing
with tf.Session() as sess:
        result = sess.run(fill_mat)
print(result)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [19]:
#Declaring a null matrix 4,4
my_zeros = tf.zeros((4,4))
#Declaring a matrix 4x4 with random values from a Z distribution
myrandn = tf.random_normal((4,4), mean = 0, stddev=1.0)
#and adding them up
matrix_addition = my_zeros+myrandn

In [20]:
#Storing my operations in a list
my_ops = [fill_mat, my_zeros, myrandn, matrix_addition]

In [21]:
#Printing with a for loop after reopening a session
with tf.Session() as sess:
    for op in my_ops:
       print (sess.run(op))
       print ('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.98510075  0.62867135  0.82448214 -0.52605486]
 [ 0.5295306   0.5632194  -0.24680364  1.8775233 ]
 [-0.04176605  0.93058085 -0.02501958 -0.07123469]
 [ 0.83225477 -0.74362195  0.00802465 -1.5790066 ]]


[[ 1.4737717   0.12924485 -1.7723336   0.99051666]
 [-0.98383003 -0.3755623  -0.49169952  1.3076925 ]
 [ 0.82854223  0.8828522  -0.4625403  -0.8008381 ]
 [-0.02680367  0.05891848 -0.32213354  1.0086395 ]]




In [22]:
sess.close()